export interface CurrencyOption {
  value: string;
  label: string;
  description: string;
}

// ISO 4217 — full list of active currencies with their symbols and English names.
export const CURRENCIES: CurrencyOption[] = [
  { value: 'AED', label: 'AED (د.إ)', description: 'UAE Dirham' },
  { value: 'AFN', label: 'AFN (؋)', description: 'Afghan Afghani' },
  { value: 'ALL', label: 'ALL (L)', description: 'Albanian Lek' },
  { value: 'AMD', label: 'AMD (֏)', description: 'Armenian Dram' },
  { value: 'ANG', label: 'ANG (ƒ)', description: 'Netherlands Antillean Guilder' },
  { value: 'AOA', label: 'AOA (Kz)', description: 'Angolan Kwanza' },
  { value: 'ARS', label: 'ARS ($)', description: 'Argentine Peso' },
  { value: 'AUD', label: 'AUD (A$)', description: 'Australian Dollar' },
  { value: 'AWG', label: 'AWG (ƒ)', description: 'Aruban Florin' },
  { value: 'AZN', label: 'AZN (₼)', description: 'Azerbaijani Manat' },
  { value: 'BAM', label: 'BAM (KM)', description: 'Bosnia-Herzegovina Convertible Mark' },
  { value: 'BBD', label: 'BBD ($)', description: 'Barbadian Dollar' },
  { value: 'BDT', label: 'BDT (৳)', description: 'Bangladeshi Taka' },
  { value: 'BGN', label: 'BGN (лв)', description: 'Bulgarian Lev' },
  { value: 'BHD', label: 'BHD (.د.ب)', description: 'Bahraini Dinar' },
  { value: 'BIF', label: 'BIF (FBu)', description: 'Burundian Franc' },
  { value: 'BMD', label: 'BMD ($)', description: 'Bermudian Dollar' },
  { value: 'BND', label: 'BND ($)', description: 'Brunei Dollar' },
  { value: 'BOB', label: 'BOB (Bs.)', description: 'Bolivian Boliviano' },
  { value: 'BRL', label: 'BRL (R$)', description: 'Brazilian Real' },
  { value: 'BSD', label: 'BSD ($)', description: 'Bahamian Dollar' },
  { value: 'BTN', label: 'BTN (Nu.)', description: 'Bhutanese Ngultrum' },
  { value: 'BWP', label: 'BWP (P)', description: 'Botswanan Pula' },
  { value: 'BYN', label: 'BYN (Br)', description: 'Belarusian Ruble' },
  { value: 'BZD', label: 'BZD (BZ$)', description: 'Belize Dollar' },
  { value: 'CAD', label: 'CAD (C$)', description: 'Canadian Dollar' },
  { value: 'CDF', label: 'CDF (FC)', description: 'Congolese Franc' },
  { value: 'CHF', label: 'CHF (Fr)', description: 'Swiss Franc' },
  { value: 'CLP', label: 'CLP ($)', description: 'Chilean Peso' },
  { value: 'CNY', label: 'CNY (¥)', description: 'Chinese Yuan' },
  { value: 'COP', label: 'COP ($)', description: 'Colombian Peso' },
  { value: 'CRC', label: 'CRC (₡)', description: 'Costa Rican Colón' },
  { value: 'CUP', label: 'CUP ($)', description: 'Cuban Peso' },
  { value: 'CVE', label: 'CVE (Esc)', description: 'Cape Verdean Escudo' },
  { value: 'CZK', label: 'CZK (Kč)', description: 'Czech Koruna' },
  { value: 'DJF', label: 'DJF (Fdj)', description: 'Djiboutian Franc' },
  { value: 'DKK', label: 'DKK (kr)', description: 'Danish Krone' },
  { value: 'DOP', label: 'DOP (RD$)', description: 'Dominican Peso' },
  { value: 'DZD', label: 'DZD (د.ج)', description: 'Algerian Dinar' },
  { value: 'EGP', label: 'EGP (£)', description: 'Egyptian Pound' },
  { value: 'ERN', label: 'ERN (Nfk)', description: 'Eritrean Nakfa' },
  { value: 'ETB', label: 'ETB (Br)', description: 'Ethiopian Birr' },
  { value: 'EUR', label: 'EUR (€)', description: 'Euro' },
  { value: 'FJD', label: 'FJD ($)', description: 'Fijian Dollar' },
  { value: 'FKP', label: 'FKP (£)', description: 'Falkland Islands Pound' },
  { value: 'GBP', label: 'GBP (£)', description: 'British Pound' },
  { value: 'GEL', label: 'GEL (₾)', description: 'Georgian Lari' },
  { value: 'GHS', label: 'GHS (₵)', description: 'Ghanaian Cedi' },
  { value: 'GIP', label: 'GIP (£)', description: 'Gibraltar Pound' },
  { value: 'GMD', label: 'GMD (D)', description: 'Gambian Dalasi' },
  { value: 'GNF', label: 'GNF (FG)', description: 'Guinean Franc' },
  { value: 'GTQ', label: 'GTQ (Q)', description: 'Guatemalan Quetzal' },
  { value: 'GYD', label: 'GYD ($)', description: 'Guyanaese Dollar' },
  { value: 'HKD', label: 'HKD (HK$)', description: 'Hong Kong Dollar' },
  { value: 'HNL', label: 'HNL (L)', description: 'Honduran Lempira' },
  { value: 'HTG', label: 'HTG (G)', description: 'Haitian Gourde' },
  { value: 'HUF', label: 'HUF (Ft)', description: 'Hungarian Forint' },
  { value: 'IDR', label: 'IDR (Rp)', description: 'Indonesian Rupiah' },
  { value: 'ILS', label: 'ILS (₪)', description: 'Israeli New Shekel' },
  { value: 'INR', label: 'INR (₹)', description: 'Indian Rupee' },
  { value: 'IQD', label: 'IQD (ع.د)', description: 'Iraqi Dinar' },
  { value: 'IRR', label: 'IRR (﷼)', description: 'Iranian Rial' },
  { value: 'ISK', label: 'ISK (kr)', description: 'Icelandic Króna' },
  { value: 'JMD', label: 'JMD (J$)', description: 'Jamaican Dollar' },
  { value: 'JOD', label: 'JOD (د.ا)', description: 'Jordanian Dinar' },
  { value: 'JPY', label: 'JPY (¥)', description: 'Japanese Yen' },
  { value: 'KES', label: 'KES (KSh)', description: 'Kenyan Shilling' },
  { value: 'KGS', label: 'KGS (с)', description: 'Kyrgystani Som' },
  { value: 'KHR', label: 'KHR (៛)', description: 'Cambodian Riel' },
  { value: 'KMF', label: 'KMF (CF)', description: 'Comorian Franc' },
  { value: 'KPW', label: 'KPW (₩)', description: 'North Korean Won' },
  { value: 'KRW', label: 'KRW (₩)', description: 'South Korean Won' },
  { value: 'KWD', label: 'KWD (د.ك)', description: 'Kuwaiti Dinar' },
  { value: 'KYD', label: 'KYD ($)', description: 'Cayman Islands Dollar' },
  { value: 'KZT', label: 'KZT (₸)', description: 'Kazakhstani Tenge' },
  { value: 'LAK', label: 'LAK (₭)', description: 'Laotian Kip' },
  { value: 'LBP', label: 'LBP (ل.ل)', description: 'Lebanese Pound' },
  { value: 'LKR', label: 'LKR (Rs)', description: 'Sri Lankan Rupee' },
  { value: 'LRD', label: 'LRD ($)', description: 'Liberian Dollar' },
  { value: 'LSL', label: 'LSL (L)', description: 'Lesotho Loti' },
  { value: 'LYD', label: 'LYD (ل.د)', description: 'Libyan Dinar' },
  { value: 'MAD', label: 'MAD (د.م.)', description: 'Moroccan Dirham' },
  { value: 'MDL', label: 'MDL (L)', description: 'Moldovan Leu' },
  { value: 'MGA', label: 'MGA (Ar)', description: 'Malagasy Ariary' },
  { value: 'MKD', label: 'MKD (ден)', description: 'Macedonian Denar' },
  { value: 'MMK', label: 'MMK (K)', description: 'Myanmar Kyat' },
  { value: 'MNT', label: 'MNT (₮)', description: 'Mongolian Tugrik' },
  { value: 'MOP', label: 'MOP (MOP$)', description: 'Macanese Pataca' },
  { value: 'MRU', label: 'MRU (UM)', description: 'Mauritanian Ouguiya' },
  { value: 'MUR', label: 'MUR (₨)', description: 'Mauritian Rupee' },
  { value: 'MVR', label: 'MVR (.ރ)', description: 'Maldivian Rufiyaa' },
  { value: 'MWK', label: 'MWK (MK)', description: 'Malawian Kwacha' },
  { value: 'MXN', label: 'MXN ($)', description: 'Mexican Peso' },
  { value: 'MYR', label: 'MYR (RM)', description: 'Malaysian Ringgit' },
  { value: 'MZN', label: 'MZN (MT)', description: 'Mozambican Metical' },
  { value: 'NAD', label: 'NAD ($)', description: 'Namibian Dollar' },
  { value: 'NGN', label: 'NGN (₦)', description: 'Nigerian Naira' },
  { value: 'NIO', label: 'NIO (C$)', description: 'Nicaraguan Córdoba' },
  { value: 'NOK', label: 'NOK (kr)', description: 'Norwegian Krone' },
  { value: 'NPR', label: 'NPR (₨)', description: 'Nepalese Rupee' },
  { value: 'NZD', label: 'NZD (NZ$)', description: 'New Zealand Dollar' },
  { value: 'OMR', label: 'OMR (ر.ع.)', description: 'Omani Rial' },
  { value: 'PAB', label: 'PAB (B/.)', description: 'Panamanian Balboa' },
  { value: 'PEN', label: 'PEN (S/)', description: 'Peruvian Sol' },
  { value: 'PGK', label: 'PGK (K)', description: 'Papua New Guinean Kina' },
  { value: 'PHP', label: 'PHP (₱)', description: 'Philippine Peso' },
  { value: 'PKR', label: 'PKR (₨)', description: 'Pakistani Rupee' },
  { value: 'PLN', label: 'PLN (zł)', description: 'Polish Złoty' },
  { value: 'PYG', label: 'PYG (₲)', description: 'Paraguayan Guarani' },
  { value: 'QAR', label: 'QAR (ر.ق)', description: 'Qatari Riyal' },
  { value: 'RON', label: 'RON (lei)', description: 'Romanian Leu' },
  { value: 'RSD', label: 'RSD (дин)', description: 'Serbian Dinar' },
  { value: 'RUB', label: 'RUB (₽)', description: 'Russian Ruble' },
  { value: 'RWF', label: 'RWF (FRw)', description: 'Rwandan Franc' },
  { value: 'SAR', label: 'SAR (﷼)', description: 'Saudi Riyal' },
  { value: 'SBD', label: 'SBD ($)', description: 'Solomon Islands Dollar' },
  { value: 'SCR', label: 'SCR (₨)', description: 'Seychellois Rupee' },
  { value: 'SDG', label: 'SDG (ج.س.)', description: 'Sudanese Pound' },
  { value: 'SEK', label: 'SEK (kr)', description: 'Swedish Krona' },
  { value: 'SGD', label: 'SGD (S$)', description: 'Singapore Dollar' },
  { value: 'SHP', label: 'SHP (£)', description: 'Saint Helena Pound' },
  { value: 'SLE', label: 'SLE (Le)', description: 'Sierra Leonean Leone' },
  { value: 'SOS', label: 'SOS (S)', description: 'Somali Shilling' },
  { value: 'SRD', label: 'SRD ($)', description: 'Surinamese Dollar' },
  { value: 'SSP', label: 'SSP (£)', description: 'South Sudanese Pound' },
  { value: 'STN', label: 'STN (Db)', description: 'São Tomé and Príncipe Dobra' },
  { value: 'SVC', label: 'SVC ($)', description: 'Salvadoran Colón' },
  { value: 'SYP', label: 'SYP (£)', description: 'Syrian Pound' },
  { value: 'SZL', label: 'SZL (L)', description: 'Swazi Lilangeni' },
  { value: 'THB', label: 'THB (฿)', description: 'Thai Baht' },
  { value: 'TJS', label: 'TJS (SM)', description: 'Tajikistani Somoni' },
  { value: 'TMT', label: 'TMT (m)', description: 'Turkmenistani Manat' },
  { value: 'TND', label: 'TND (د.ت)', description: 'Tunisian Dinar' },
  { value: 'TOP', label: 'TOP (T$)', description: 'Tongan Paʻanga' },
  { value: 'TRY', label: 'TRY (₺)', description: 'Turkish Lira' },
  { value: 'TTD', label: 'TTD (TT$)', description: 'Trinidad and Tobago Dollar' },
  { value: 'TWD', label: 'TWD (NT$)', description: 'New Taiwan Dollar' },
  { value: 'TZS', label: 'TZS (TSh)', description: 'Tanzanian Shilling' },
  { value: 'UAH', label: 'UAH (₴)', description: 'Ukrainian Hryvnia' },
  { value: 'UGX', label: 'UGX (USh)', description: 'Ugandan Shilling' },
  { value: 'USD', label: 'USD ($)', description: 'US Dollar' },
  { value: 'UYU', label: 'UYU ($U)', description: 'Uruguayan Peso' },
  { value: 'UZS', label: 'UZS (сўм)', description: 'Uzbekistani Som' },
  { value: 'VES', label: 'VES (Bs)', description: 'Venezuelan Bolívar' },
  { value: 'VND', label: 'VND (₫)', description: 'Vietnamese Dong' },
  { value: 'VUV', label: 'VUV (VT)', description: 'Vanuatu Vatu' },
  { value: 'WST', label: 'WST (T)', description: 'Samoan Tala' },
  { value: 'XAF', label: 'XAF (FCFA)', description: 'Central African CFA Franc' },
  { value: 'XCD', label: 'XCD ($)', description: 'East Caribbean Dollar' },
  { value: 'XOF', label: 'XOF (CFA)', description: 'West African CFA Franc' },
  { value: 'XPF', label: 'XPF (₣)', description: 'CFP Franc' },
  { value: 'YER', label: 'YER (﷼)', description: 'Yemeni Rial' },
  { value: 'ZAR', label: 'ZAR (R)', description: 'South African Rand' },
  { value: 'ZMW', label: 'ZMW (ZK)', description: 'Zambian Kwacha' },
  { value: 'ZWL', label: 'ZWL ($)', description: 'Zimbabwean Dollar' },
];
